### ISSUE TITLE
Automatically update README when publishing to Docker Hub

### ISSUE THREAD

**Issue by pascalberger** [swissgrc/docker-azure-pipelines-openjdk#17]
README on Docker Hub currently needs to be updated manually. It would be nice if README would be automatically updated every time a new image is pushed to Docker Hub

**Comment by grc0** [comment]
> 

Which user is needed to update the readme on Docker Hub?

**Comment by pascalberger** [comment]
`DOCKER_USERNAME` and `DOCKER_PASSWORD` secrets are available to GitHub actions. 

See here for an example:

https://github.com/swissgrc/docker-azure-pipelines-openjdk/blob/87439b2a8c54dca593cd7a2a5179db1c131463c9/.github/workflows/publish.yml#L61-L62

**Comment by pascalberger** [comment]
This can be implemented using a GitHub Action like  https://github.com/marketplace/actions/docker-hub-description
